apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ${grafana_certificate_name}
  namespace: "${namespace}"
spec:
  secretName: "${grafana_certificate_secret_name}"
  issuerRef:
    name: ${issuer_name}
    kind: ClusterIssuer
  commonName: "${grafana_host}"
  dnsNames:
    - "${grafana_host}"
