apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "${certificate_name}"
  namespace: "${certificate_namespace}"
spec:
  secretName: "${certificate_secret_name}"
  issuerRef:
    name: ${issuer_name}
    kind: ClusterIssuer
  commonName: "${certificate_base_hostname}"
  dnsNames:
    - "${certificate_base_hostname}"
    - "*.${certificate_base_hostname}"
